[tools]
go = "1.25.2"

[[env]]
GOPRIVATE = "github.com/palanquin-software/*"

[tasks.install]
run = '''
cd cmd/mcp
go build -o {{env.HOME}}/bin/mcp-internet-archive
chmod +x {{env.HOME}}/bin/mcp-internet-archive
echo Installed mcp-internet-archive to {{env.HOME}}/bin/mcp-internet-archive
'''
